litex: adding litespi to simulation, making litespi compatible with new implementation
antmicro/litex pull request #7
Opened 2021-09-01 08:51 UTC by pawelsag

2021-09-01 09:08 UTC, piotr-binkowski requested changes

2021-09-01 09:08 UTC, piotr-binkowski commented on litex/tools/litex_sim.py
> +        IOStandard("LVCMOS33"),
I think we can use simply `Pins(n)` where `n` is signal width and remove `IOStandard` since it is not important in simulation

2021-09-01 09:08 UTC, piotr-binkowski commented on litex/soc/software/liblitespi/spiflash.c
> -	printf("SPI Flash clk configured to %d MHz\n", (spiflash_core_sys_clk_freq_read()/(2*(1 + lowest_div)))/1000000);
I think we wanted to keep this message in some form

2021-09-02 10:35 UTC, pawelsag commented on litex/soc/software/liblitespi/spiflash.c
> -	printf("SPI Flash clk configured to %d MHz\n", (spiflash_core_sys_clk_freq_read()/(2*(1 + lowest_div)))/1000000);
The msg was restored

2021-09-02 12:16 UTC, closed without merging